version: '3'
services:
  app:
    build:
      context: .
      args:
        buildno: 1
    container_name: fixme
    command: fixme -v debug run -p 8080 --address 0.0.0.0
    ports:
      - 8080:8080
    volumes:
      - .:/home/rust/src
